### ISSUE TITLE
LSAutoTimeZone.py might not be 10.12 friendly

### ISSUE THREAD

**Issue by clburlison** [clburlison/scripts#3]
Have a report that `LSAutoTimeZone.py` isn't working to nicely on 10.12 (Sierra).

I'll try and verify/fix if I can come up with something. Evidently it's the `timezone_lookup()` function.

https://github.com/clburlison/scripts/blob/75d46c1b53f11920abbc4507d8d284782cfd1cd0/clburlison_scripts/LSAutoTimeZone/LSAutoTimeZone.py#L153-L163

**Comment by clburlison** [comment]
The real error is most likely actually happening in the `sysprefs_boxchk` function. We should do error handling in the `timezone_lookup` function to make sure that LS is actually enabled (IE steal the code from pinpoint).

**Comment by clburlison** [comment]
The root issue is I'm unable to start/stop Location Services on Sierra with: `sudo launchctl load /System/Library/LaunchDaemons/com.apple.locationd.plist`

**Comment by clburlison** [comment]
Loading isn't the actual issue. Preference caching is causing the issue. Fix is already in pinpoint just need to port it over. https://github.com/clburlison/pinpoint/commit/18ea1fcc60b47dbf89dc538f0c0adc18454a76da#diff-9cee2e349b1920be4296162259506b00R251

**Comment by ehemmete** [comment]
I am seeing a Segmentation fault: 11 when trying this in 10.12.1.  It seems specifically to happen in the timezone_lookup() function.

**Comment by clburlison** [comment]
Yeah. I'm aware of the issue and fix. I should get around to fixing it... (sorry been a bit busy)

**Comment by clburlison** [comment]
Hey @ehemmete, you motivated me to fix this. It now works with 10.12. Let me know if you run into issues.

CC: @chilcote (at one point you were interested in this script)

**Comment by ehemmete** [comment]
Sweet!  Thank you. I'll test it tomorrow. 

Eric

**Comment by chilcote** [comment]
Thankye
